services:

  # PostgreSQL service configuration
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data  # Specifies the data directory
    volumes:
      - postgres:/var/lib/postgresql/data  # Maps data to the named volume 'postgres' for persistence
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  # pgAdmin service configuration
  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80  # Maps port 5050 on the host to port 80 in the container
    networks:
      - microservices-net
    restart: unless-stopped

  # MongoDB service configuration
  mongodb:
    container_name: ms_mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - microservices-net
    restart: unless-stopped

  # Mongo Express (MongoDB GUI) configuration
  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    networks:
      - microservices-net
    restart: unless-stopped

  # MailDev service configuration
  maildev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net
    restart: unless-stopped

# Define the shared network for all services
networks:
  microservices-net:
    driver: bridge

# Define named volumes for data persistence across container restarts
volumes:
  postgres:
  pgadmin:
  mongo:
